brew "fzf"
brew "gh"
brew "git"
brew "htop"
brew "lazygit"
brew "lazydocker"
brew "node"
brew "tmux"
brew "choose-gui"
brew "mosh"
brew "corepack"
brew "python"
brew "nvim"
brew "chezmoi"

cask "hiddenbar"
cask "font-meslo-lg-nerd-font"
cask "font-meslo-for-powerline"
